const USER_REQUEST = 'USER_REQUEST'
const USER_SUCCESS = 'USER_SUCCESS'
const USER_ERROR = 'USER_ERROR'
const USER_LOGOUT = 'USER_LOGOUT'

export {
    USER_REQUEST,
    USER_SUCCESS,
    USER_ERROR,
    USER_LOGOUT,
}