const USER_REQUEST = 'USER_REQUEST'
const USER_SUCCESS = 'USER_SUCCESS'
const USER_ERROR = 'USER_ERROR'
const USER_UPDATE_REQUEST = 'USER_REQUEST'
const USER_UPDATE_SUCCESS = 'USER_SUCCESS'
const USER_UPDATE_ERROR = 'USER_ERROR'
const USER_LOGIN = 'USER_LOGIN'
const USER_LOGOUT = 'USER_LOGOUT'
const TOKEN_LOGIN = 'TOKEN_LOGIN'
const TOKEN_LOGOUT = 'TOKEN_LOGOUT'

export {
    USER_REQUEST,
    USER_SUCCESS,
    USER_ERROR,
    USER_UPDATE_REQUEST,
    USER_UPDATE_SUCCESS,
    USER_UPDATE_ERROR,
    USER_LOGOUT,
    USER_LOGIN,
    TOKEN_LOGIN,
    TOKEN_LOGOUT,
}