const USER_REQUEST = 'USER_REQUEST'
const USER_SUCCESS = 'USER_SUCCESS'
const USER_ERROR = 'USER_ERROR'
const AUTH_LOGOUT = 'USER_ERROR'

export {
    USER_REQUEST,
    USER_SUCCESS,
    USER_ERROR,
    AUTH_LOGOUT,
}