const FETCH_PARAMETERS = 'FETCH_PARAMETERS'
const FETCH_PARAMETERS_SUCCESS = 'FETCH_PARAMETERS_SUCESS'
const SET_GLOBAL_ERROR = 'SET_GLOBAL_ERROR'

export {
  FETCH_PARAMETERS,
  FETCH_PARAMETERS_SUCCESS,
  SET_GLOBAL_ERROR,
}