const FETCH_PARAMETERS = 'FETCH_PARAMETERS'
const FETCH_PARAMETERS_SUCCESS = 'FETCH_PARAMETERS_SUCESS'
const USER_LOGIN = 'USER_LOGIN'
const USER_LOGOUT = 'USER_LOGOUT'
const TOKEN_LOGIN = 'TOKEN_LOGIN'
const TOKEN_LOGOUT = 'TOKEN_LOGOUT'

export {
  FETCH_PARAMETERS,
  FETCH_PARAMETERS_SUCCESS,
  USER_LOGOUT,
  USER_LOGIN,
  TOKEN_LOGIN,
  TOKEN_LOGOUT,
}