const ACTIVITY_REQUEST = 'ACTIVITY_REQUEST'
const ACTIVITY_SUCCESS = 'ACTIVITY_SUCCESS'
const ACTIVITY_ERROR = 'ACTIVITY_ERROR'

export {
    ACTIVITY_REQUEST,
    ACTIVITY_SUCCESS,
    ACTIVITY_ERROR,
}